// Code generated by mockery v1.0.0

// This comment works around https://github.com/vektra/mockery/issues/155

package instances

import compute "google.golang.org/api/compute/v1"
import mock "github.com/stretchr/testify/mock"
import prometheus "github.com/prometheus/client_golang/prometheus"

// mockCounterInterface is an autogenerated mock type for the counterInterface type
type mockCounterInterface struct {
	mock.Mock
}

// Add provides a mock function with given fields: project, zone, instances
func (_m *mockCounterInterface) Add(project string, zone string, instances []*compute.Instance) {
	_m.Called(project, zone, instances)
}

// Collect provides a mock function with given fields: ch
func (_m *mockCounterInterface) Collect(ch chan<- prometheus.Metric) {
	_m.Called(ch)
}
