// Code generated by mockery v1.0.0

// This comment works around https://github.com/vektra/mockery/issues/155

package services

import context "context"
import http "net/http"
import mock "github.com/stretchr/testify/mock"

// MockHTTPServerInterface is an autogenerated mock type for the HTTPServerInterface type
type MockHTTPServerInterface struct {
	mock.Mock
}

// ListenAndServe provides a mock function with given fields:
func (_m *MockHTTPServerInterface) ListenAndServe() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAddr provides a mock function with given fields: _a0
func (_m *MockHTTPServerInterface) SetAddr(_a0 string) {
	_m.Called(_a0)
}

// SetContext provides a mock function with given fields: _a0
func (_m *MockHTTPServerInterface) SetContext(_a0 context.Context) {
	_m.Called(_a0)
}

// SetHandler provides a mock function with given fields: _a0
func (_m *MockHTTPServerInterface) SetHandler(_a0 http.Handler) {
	_m.Called(_a0)
}
