#!/usr/bin/env bash

set -eo pipefail

IMAGE="${CI_IMAGE}"

source ./scripts/docker_support

login
pull

echo "Building image"
docker build --cache-from ${IMAGE} -t ${IMAGE} -f ./dockerfiles/ci/Dockerfile ./dockerfiles/ci

push
logout