// Code generated by mockery v1.0.0

// This comment works around https://github.com/vektra/mockery/issues/155

package services

import compute "google.golang.org/api/compute/v1"
import context "context"
import mock "github.com/stretchr/testify/mock"

// MockComputeServiceInterface is an autogenerated mock type for the ComputeServiceInterface type
type MockComputeServiceInterface struct {
	mock.Mock
}

// GetRegion provides a mock function with given fields: ctx, project, region
func (_m *MockComputeServiceInterface) GetRegion(ctx context.Context, project string, region string) (*compute.Region, error) {
	ret := _m.Called(ctx, project, region)

	var r0 *compute.Region
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *compute.Region); ok {
		r0 = rf(ctx, project, region)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*compute.Region)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, project, region)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListInstances provides a mock function with given fields: ctx, project, zone, perPage
func (_m *MockComputeServiceInterface) ListInstances(ctx context.Context, project string, zone string, perPage int64) ([]*compute.Instance, error) {
	ret := _m.Called(ctx, project, zone, perPage)

	var r0 []*compute.Instance
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) []*compute.Instance); ok {
		r0 = rf(ctx, project, zone, perPage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*compute.Instance)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = rf(ctx, project, zone, perPage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
